sudo: false
dist: trusty
sudo: required
language: python
python:
  - "2.7"
before_install:
  - wget 'http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh' -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - sudo apt-get update
  - sudo apt-get install libc6
install:
  - conda create --yes -n shorttext-test python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - source activate shorttext-test
  - pip install unittest
  - pip install tensorflow
  - pip install -U .
  - spacy download en
script:
  - python setup.py test
