sudo: true
dist: xenial
sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - wget 'http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh' -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - sudo apt-get update
  - sudo apt-get install libc6
  - conda install --yes libgcc
install:
  - conda create --yes -n shorttext-test python=$TRAVIS_PYTHON_VERSION
  - source activate shorttext-test
  - pip install Cython
  - pip install -U numpy
  - pip install -U scipy
  - pip install google-compute-engine
  - pip install -U tensorflow
  - pip install -U .
  - spacy download en
script:
  - python setup.py test
